services:
  backend:
    build:
      context: ../server
      dockerfile: Dockerfile
    restart: always
    environment:
      - DATABASE=172.17.0.1
    ports:
      - "8000:8000"
    expose:
      - "8000"
  nginx:
    image: nginx:1.25.3
    ports:
      - "80:80"
    volumes:
      - ../client/build:/usr/share/nginx/html
      - ./nginx/prod/default.conf:/etc/nginx/conf.d/default.conf
      - /opt/certs/cloudflare.key:/etc/ssl/private/cloudflare.key:ro
      - /opt/certs/cloudflare.pem:/etc/ssl/certs/cloudflare.pem:ro
    depends_on:
      - backend
