services:
  backend:
    build:
      context: ../server
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DATABASE=host.docker.internal
    ports:
      - 8000:8000
    expose:
      - 8000
    env_file:
      - ../server/.env

  nginx:
    image: nginx:1.23.3
    ports:
      - 80:80
    volumes:
      - ../client/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
