services:
  backend:
    build:
      context: ../server
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DATABASE=host.docker.internal
    ports:
      - "8000:8000"
    expose:
      - "8000"

  nginx:
    build:
      context: ../client
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../client/build:/urs/share/nginx/html
      - ./nginx/prod/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot

  certbot:
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done'"
