services:
  backend:
    build:
      context: ../server
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DATABASE=host.docker.internal
      - CLIENT_URL=http://localhost
    ports:
      - 8000:8000
    expose:
      - 8000

  nginx:
    image: nginx:1.25.3
    ports:
      - 80:80
    volumes:
      - ../client/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
